apiVersion: apps/v1
kind: Deployment
metadata:
  name: thaye
  labels:
    app: thaye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thaye
  template:
    metadata:
      name: thaye
      labels:
        app: thaye
    spec:
      containers:
        - name: thaye
          image: ghcr.io/zgamelogic/thaye:master
          imagePullPolicy: Always
          volumeMounts:
            - name: keystore-volume
              mountPath: "/etc/keystore"
              readOnly: true
          env:
            - name: TZ
              value: "America/Chicago"
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: keystore-volume
          secret:
            secretName: ssl-keystore-secret
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret

      