name: Deploy Thaye

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-deploy.yaml@0.0.1
    with:
      applicationId: 7
      monitorIds: '7'
      environment: production
      deploymentName: thaye
      imageName: thaye