name: Deploy Thaye

on:
  push:
    branches: [ "master" ]
    ##  uses: zgamelogic/data-otter-monitor-active/.github/workflows/action.yml@v1.0.2
jobs:
  disable-monitor:
    uses: zgamelogic/github-actions/actions/kubernetes-spring/kubernetes-deploy.yaml@0.0.1
    with:
      applicationId: 7
      monitorIds: '7'
      environment: production
      deploymentName: thaye
      imageName: thaye