name: Deploy Thaye

on:
  push:
    branches: [ "master" ]
jobs:
  disable-monitor:
    uses: zgamelogic/github-actions/.github/workflows/kubernetes-spring/kubernetes-deploy.yaml@0.0.1
    with:
      applicationId: 7
      monitorIds: '7'
      environment: production
      deploymentName: thaye
      imageName: thaye